#+title: Giochi di Banach-Mazur
#+author: Davide Peccioli
#+date: 4 giugno 2025

#+startup: beamer
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [babel]
#+BEAMER_THEME: CambridgeUS
#+BEAMER_COLOR_THEME: spruce
#+BEAMER_FONT_THEME: professionalfonts
#+LaTeX_HEADER: \institute[]{Università degli Studi di Torino}
#+LaTeX_HEADER: \input{header_beamer.tex}
#+LaTeX_HEADER: \hypersetup{pdfpagemode=FullScreen}
#+OPTIONS: H:2 toc:nil
#+LATEX_HEADER: \renewcommand{\href}[2]{#2}

* Teoria dei Giochi

** Gioco Logico

*** Definizione 1.1
:PROPERTIES:
:BEAMER_env: block
:END:

Un _gioco logico_ è una quadrupla \(\mathcal{G} \coloneqq (\Omega, f, W_{\text{I}}, W_{\text{II}})\) dove:
- \(\Omega\) è un [[id:76c41141-40b1-420e-89bc-6da6d94d2509][insieme]], chiamato il _dominio del gioco_;
- \(f:\Omega^{<\omega}\to \set{\text{I},\text{II}}\) è una [[id:40832c72-9f3d-442f-b03a-d8a1ae32774f][funzione]], chiamata _funzione di turno_ o _funzione del giocatore_;
- \(W_{\text{I}},W_{\text{II}} \subseteq \Omega^{<\omega}\cup \Omega^{\omega}\) sono tali che
  a. \(W_{\text{I}}\cap W_{\text{II}} = \emptyset\);
  b. per ogni \(\bm{a} \in W_{\bullet}\) e per ogni \(\bm{b} \in\Omega^{<\omega}\cup \Omega^{\omega}\):
  \begin{equation*}
	\bm{a} \subseteq \bm{b}\quad\implies\quad \bm{b} \in W_{\bullet}
  \end{equation*}

Gli elementi di \(\Omega^{<\omega}\) sono chiamati _posizioni del gioco_ \(\mathcal{G}\), mentre un elemento di \(\Omega^{\omega}\) è detto _giocata_ di \(\mathcal{G}\).

** DA TOGLIERE

I giocatori I e II giocano scegliendo a turno elementi di \(\Omega\). La funzione di turno \(f\) associa a ciascuna posizione uno dei due giocatori: se
\begin{equation*}
f(a_{0},a_{1},\dots,a_{n}) = \text{I}
\end{equation*}
allora l'elemento \(a_{n+1}\) sarà scelto dal giocatore I.

Si dirà che il giocatore I _vince la giocata \(\bm{a}\)_ se \(\bm{a} \in W_{\text{I}}\); si dirà che il giocatore II _vince la giocata \(\bm{b}\)_ se \(\bm{b} \in W_{\text{II}}\).

*** Definizione 1.2
:PROPERTIES:
:BEAMER_env: block
:END:

Un gioco è detto _totale_ se \(\Omega^{\omega} \subseteq W_{\text{I}}\cup W_{\text{II}}\).

** Strategia per un gioco logico

Una strategia per un giocatore è un insieme di regole che descrivono esattamente come un giocatore debba giocare, in base a tutte le mosse precedenti.

Una strategia è dettoa _vincente_ per un giocatore se questo vince ogni giocata in cui ne fa uso, a prescindere dalle mosse dell'altro giocatore.

*** Definizione 1.4
:PROPERTIES:
:BEAMER_env: block
:END:

Un gioco si dice _determinato_ se esiste una strategia vincente per I o per II.

** Giochi logici equivalenti

*** Definizione 1.5
:PROPERTIES:
:BEAMER_env: block
:END:

Due [[id:90b2021f-dbe8-499f-8c79-32379384fdb8][giochi logici]] \(\mathcal{G}\) e \(\mathcal{G'}\) con giocatori I e II sono detti _equivalenti_ se sono soddisfate entrambe le seguenti ipotsi:
a. esiste una [[id:2f1132b9-a68c-42dc-b889-f9ea0565677f][strategia vincente]] per I in \(\mathcal{G}\) sse esiste una [[id:2f1132b9-a68c-42dc-b889-f9ea0565677f][strategia vincente]] per I in \(\mathcal{G}'\)
b. esiste una [[id:2f1132b9-a68c-42dc-b889-f9ea0565677f][strategia vincente]] per II in \(\mathcal{G}\) sse esiste una [[id:2f1132b9-a68c-42dc-b889-f9ea0565677f][strategia vincente]] per II in \(\mathcal{G}'\)

** Giochi di Gale-Stewart

*** Definizione 1.6
:PROPERTIES:
:BEAMER_env: block
:END:

Sia \(A\) un [[id:76c41141-40b1-420e-89bc-6da6d94d2509][insieme]] non vuoto, e sia \(C \subseteq A^{\omega}\). Si definisce il _gioco di Gale-Stewart_ associato ad \(C\) come il [[id:90b2021f-dbe8-499f-8c79-32379384fdb8][gioco logico]] seguente:
\begin{equation*}
G(A,C) = G(A) \coloneqq (A, \psi, C, A^{\omega}\setminus C)
\end{equation*}
dove la [[id:40832c72-9f3d-442f-b03a-d8a1ae32774f][funzione]] \(\psi: A^{<\omega}\to \set{\text{I},\text{II}}\) è così definita
\begin{equation*}
\psi(s) \coloneqq \begin{cases}
\text{I} & \operatorname{lh}(s)\text{ è pari}\\
\text{II} & \operatorname{lh}(s)\text{ è dispari}
\end{cases}
\end{equation*}

** DA TOGLIERE

Pertanto il gioco può essere codificato come segue:
\begin{equation*}
\begin{tikzcd}[ampersand replacement=\&,cramped,sep=tiny]
	{\text{I}} \& {a_0} \&\& {a_2} \&\& {a_4} \&\& \dots \\
	{\text{II}} \&\& {a_1} \&\& {a_3} \&\& \dots
\end{tikzcd}
\end{equation*}
e il giocatore I vince se e solo se \((a_{n})_{n \in \omega} \in C\).

** Strategia per un gioco di Gale-Stewart
Si specializza la definizione di [[id:2f1132b9-a68c-42dc-b889-f9ea0565677f][strategia per un gioco logico]] al caso particolare di un gioco di Gale-Stewart.

Una strategia per un gioco \(G(A,C)\) è un [[id:f6a088d6-177a-4efe-94de-06619dfaa3ec][albero]] \(\sigma \subseteq A^{<\omega}\) tale che:
   a. \(\sigma\) sia [[id:a2f6fcaa-d386-4adb-a8b8-34e590e42140][potato]] e non vuoto;

   b. se \(\langle a_{0},\dots,a_{2j}\rangle \in \sigma\) allora per ogni \(a_{2j+1} \in A\): \(\langle a_{0},\dots,a_{2j+1}\rangle \in \sigma\);

   c. se \(\langle a_{0},\dots,a_{2j-1}\rangle \in \sigma\) allora esiste un unico \(a_{2j} \in A\) tale che \(\langle a_{0},\dots,a_{2j}\rangle \in \sigma\).

Una strategia è detta _vincente_ se il suo [[id:8338ba93-b2e9-4671-9097-4c88f5b51d46][corpo]] \([\sigma] \in A\).

** Gioco di Gale-Stewart con posizioni ammissibili

Spesso è comodo considerare giochi in cui I e II non possano giocare ogni elemento di \(A\), ma debbano seguire delle _regole_. Quindi, è necessario dare un alberto potato non vuoto \(T \subseteq A^{<\omega}\), che determina le [[id:3fa552b8-abc8-4a29-9f39-144dd774974d][_posizioni ammissibili_]].

In questa situazione I e II si alternano giocando \(\langle a_{0},\dots,a_{n},\dots,\rangle\) in maniera tale che, ad ogni passo \(n \in \omega\)
\begin{equation*}
\langle a_{0},\dots,a_{n}\rangle \in T
\end{equation*}

Si scriverà, in questo caso, \(G(T, C)\).

** Teorema di Gale-Stewart

Sia \(A\) uno [[id:0739c4de-6fe4-43d3-bca9-33455ef06da8][spazio topologico]] [[id:6d05dcb7-b447-4583-91f0-9f3228435c27][discreto]] e sia \(A^{\omega}\) dotato della [[id:88fa98ee-2e42-41b3-b12e-b7a4075399da][topologia prodotto]].

*** Teorema di Gale-Stewart 1.7
:PROPERTIES:
:BEAMER_env: alertblock
:END:

Sia \(T\) un [[id:f6a088d6-177a-4efe-94de-06619dfaa3ec][albero]] [[id:a2f6fcaa-d386-4adb-a8b8-34e590e42140][potato]] non vuoto su \(A\). Se \(C \subseteq [T]\) è [[id:0739c4de-6fe4-43d3-bca9-33455ef06da8][aperto]] o [[id:0739c4de-6fe4-43d3-bca9-33455ef06da8][chiuso]] in \([T]\), allora [[id:20f27458-a0b1-4721-bd7b-04d5e882308f][il gioco]] \(G(T,C)\) è [[id:2f1132b9-a68c-42dc-b889-f9ea0565677f][determinato]].

* Insiemi Analitici e BP

** Gioco di Choquet

*** Definizione 2.1
:PROPERTIES:
:BEAMER_env: block
:END:

Sia \((X,\tau)\) uno [[id:0739c4de-6fe4-43d3-bca9-33455ef06da8][spazio topologico]] non vuoto. Il gioco di Choquet \(G_{X}\) è un [[id:90b2021f-dbe8-499f-8c79-32379384fdb8][gioco]] [[id:118a42bc-7263-46fd-92c5-85c108080240][di Gale-Stewart]] totale codificato come segue: i giocatori I e II si alternano scegliendo sottoinsiemi aperti non vuoti di \(X\):
\begin{equation*}
\begin{tikzcd}[ampersand replacement=\&,cramped,sep=tiny]
	{\text{I}} \& {U_0} \&\& {U_1} \&\& {U_2} \&\& \cdots \\
	{\text{II}} \&\& {V_0} \&\& {V_1} \&\& \cdots
\end{tikzcd}
\end{equation*}
tali che \(U_{0} \supseteq V_{0}\supseteq U_{1}\supseteq V_{1}\supseteq \dots\)

Il giocatore II vince se
\begin{equation*}
\bigcap_{n \in \omega} V_{n} = \bigcap_{n \in \omega} U_{n} \neq \emptyset.
\end{equation*}

** DA TOGLIERE

*** Teorema 2.2
:PROPERTIES:
:BEAMER_env: alertblock
:END:

Uno [[id:0739c4de-6fe4-43d3-bca9-33455ef06da8][spazio topologico]] \(X\) è uno [[id:6232eb32-a530-4c1b-aefc-403acfd7c057][spazio topologico di Baire]] se e solo se il giocatore I _non ha una [[id:25fecfe5-10ce-4072-bba1-12024479dbca][strategia]] [[id:25fecfe5-10ce-4072-bba1-12024479dbca][vincente]]_ nel [[id:eafe31ae-c3a4-4c01-97e0-a6848b6a6dc6][gioco di Choquet]] \(G_{X}\).

*** Definizione 2.3
:PROPERTIES:
:BEAMER_env: block
:END:

Uno spazio topologico \(X\) è detto _spazio di Choquet_ se il giocatore II ha una strategia vincente in \(G_{X}\).

*** DA TOGLIERE
In particolare, ogni spazio Polacco è uno spazio di Choquet.

** Gioco di Banach-Mazur

Sia \(X\) uno [[id:0739c4de-6fe4-43d3-bca9-33455ef06da8][spazio topologico]] non vuoto, e sia \(A \subseteq X\).

*** Definizione 2.5
:PROPERTIES:
:BEAMER_env: block
:END:

Il _gioco di Banach-Mazur_ (o anche **-gioco) di \(A\), denotato con \(G^{ * *}(A)\) oppure con \(G^{ * *}(A,X)\) è un [[id:90b2021f-dbe8-499f-8c79-32379384fdb8][gioco]] [[id:118a42bc-7263-46fd-92c5-85c108080240][di Gale-Stewart]] codificato come segue: i giocatori I e II si alternano scegliendo sottoinsiemi aperti non vuoti di \(X\)
\begin{equation*}
\begin{tikzcd}[ampersand replacement=\&,cramped,sep=tiny]
	{\text{I}} \& {U_0} \&\& {U_1} \&\& {U_2} \&\& \cdots \\
	{\text{II}} \&\& {V_0} \&\& {V_1} \&\& \cdots
\end{tikzcd}
\end{equation*}
[[id:20f27458-a0b1-4721-bd7b-04d5e882308f][tali che]] \(U_{0}\supseteq V_{0}\supseteq U_{1}\supseteq V_{1}\supseteq \dots\)

Il giocatore II vince se
\begin{equation*}
\bigcap_{n \in \omega} U_{n} = \bigcap_{n \in \omega} V_{n} \subseteq A.
\end{equation*}

** DA TOGLIERE

*** Teorema 2.6
:PROPERTIES:
:BEAMER_env: alertblock
:END:

Sia \(X\) uno [[id:0739c4de-6fe4-43d3-bca9-33455ef06da8][spazio topologico]] [[id:259b30b8-3c7e-407f-a372-95199bd724fa][non vuoto]], e sia \(A \subseteq X\) un [[id:fdc86b04-828f-4f24-8cdf-948211d93a95][sottoinsieme]] qualsiasi. Allora \(A\) è [[id:41953408-de97-4240-bed0-37f9de8706c4][comagro]] se e solo se il giocatore II ha una [[id:25fecfe5-10ce-4072-bba1-12024479dbca][strategia vincente]] nel [[id:00eb3064-f9f9-47c4-9eac-473caaf438a7][gioco di Banach-Mazur]] \(G^{**}(A)\).

*** Teorema 2.7
:PROPERTIES:
:BEAMER_env: alertblock
:END:

Se \(X\) è uno [[id:0739c4de-6fe4-43d3-bca9-33455ef06da8][spazio topologico]] [[id:5db440b3-d225-491e-95e4-c365595a2bca][di Choquet]] non [[id:259b30b8-3c7e-407f-a372-95199bd724fa][vuoto]] ed esiste una [[id:59033095-a7ca-4c79-92a9-c93654eb71f3][distanza]] \(d\) su \(X\) le cui [[id:ea05d3e0-5aaa-4958-9802-97dd1258ef27][palle aperte]] sono aperti di \(X\), allora:

\(A\) è [[id:41953408-de97-4240-bed0-37f9de8706c4][magro]] in un [[id:0739c4de-6fe4-43d3-bca9-33455ef06da8][aperto]] non vuoto se e solo se il giocatore I ha una [[id:25fecfe5-10ce-4072-bba1-12024479dbca][strategia vincente]] nel [[id:00eb3064-f9f9-47c4-9eac-473caaf438a7][gioco di Banach-Mazur]] \(G^{**}(A)\).

** DA TOGLIERE

Dimostrazione Teorema 2.6/2.7???

** DA TOGLIERE

*** Lemma 2.8
:PROPERTIES:
:BEAMER_env: alertblock
:END:

Sia \(X\) uno [[id:0739c4de-6fe4-43d3-bca9-33455ef06da8][spazio topologico]] [[id:5db440b3-d225-491e-95e4-c365595a2bca][di Choquet]] non [[id:259b30b8-3c7e-407f-a372-95199bd724fa][vuoto]] tale che esista una [[id:59033095-a7ca-4c79-92a9-c93654eb71f3][distanza]] \(d\) su \(X\) le cui [[id:ea05d3e0-5aaa-4958-9802-97dd1258ef27][palle aperte]] sono aperti di \(X\). Sia \(A \subseteq X\).

Se per ogni aperto \(U \subseteq X\) il [[id:00eb3064-f9f9-47c4-9eac-473caaf438a7][gioco]] \(G^{**}\left((X\setminus A)\cup U\right)\) è [[id:2f1132b9-a68c-42dc-b889-f9ea0565677f][determinato]] allora \(A \subseteq X\) ha [[id:a18bc557-1ac7-4d19-8cd8-ad3923e1a68f][BP]].

** DA TOGLIERE

*** Definizione 2.9
:PROPERTIES:
:BEAMER_env: block
:END:

Una _base debole_ per uno spazio topologico \((X,\tau)\) è una collezione di aperti \(\set{A_{\alpha}}_{\alpha \in \Omega} \subseteq \tau\) tali che, per ogni aperto non vuoto di \(X\), \(\emptyset\neq U \subseteq X\) esista \(\alpha_{0} \in \Omega\) tale che
\begin{equation*}
A_{\alpha_{0}} \subseteq U.
\end{equation*}

** Gioco di Banach-Mazur unfolded

Sia \(X\) uno [[id:c0d47e62-8d50-44c0-984a-c115c0ea2c40][spazio polacco]] non vuoto con una [[id:59033095-a7ca-4c79-92a9-c93654eb71f3][metrica]] fissata e sia \(\mathcal{W}\) una [[id:65536d5e-4a41-4b05-ad27-2594c896da4d][base debole]] [[id:43e8fa42-e06f-40fa-871f-cbc9b2387484][numerabile]] di \(X\).

*** Definizione 2.10
:PROPERTIES:
:BEAMER_env: block
:END:

Dato \(F \subseteq X\times \omega^{\omega}\), il _gioco di Banach-Mazur unfolded_ \(G^{**}_{\text{u}}(F)\) è il [[id:90b2021f-dbe8-499f-8c79-32379384fdb8][gioco]] [[id:118a42bc-7263-46fd-92c5-85c108080240][di Gale-Stewart]] codificato come segue:
\begin{equation*}
\begin{tikzcd}[ampersand replacement=\&,cramped,sep=tiny]
	{\text{I}} \& {U_0} \&\& {U_1} \&\& \dots \\
	{\text{II}} \&\& {y_0,V_0} \&\& {y_1, V_{1}} \& \dots
\end{tikzcd}
\end{equation*}
tali che:
- per ogni \(i \in \omega\): \(U_{i}, V_{i} \in \mathcal{W}\), \(y_{n} \in \omega\);
- \(\operatorname{diam}(U_{n}), \operatorname{diam}(V_{n}) < 2^{-n}\);
- \(U_{0}\supseteq V_{0}\supseteq U_{1}\supseteq V_{1}\supseteq \dots\)\hfill (continua\dots)

** DA TOGLIERE
*** Definizione 2.10
:PROPERTIES:
:BEAMER_env: block
:END:

Posto
\begin{equation*}
\set{x}\coloneqq\bigcap_{i \in \omega} \operatorname{Cl}_{X}(U_{n}) = \bigcap_{i \in \omega} \operatorname{Cl}_{X}(V_{n})
\end{equation*}
e \(y\coloneqq (y_{i})_{i \in \omega} \in \omega^{\omega}\), il _giocatore II vince_ sse
\begin{equation*}
(x,y) \in F \subseteq X\times \omega^{\omega}.
\end{equation*}

*** Lemma 2.11
:PROPERTIES:
:BEAMER_env: alertblock
:END:

Se \(F\) è aperto o chiuso di \(X\times\omega^{\omega}\), allora \(G^{**}_{\text{u}}(F)\) è determinato.

** DA TOGLIERE

*** Teorema 2.12
:PROPERTIES:
:BEAMER_env: alertblock
:END:

Sia \(X\) uno spazio polacco con una metrica fissata e sia \(\mathcal{W}\) una base debole di X.

Dato \(F \subseteq X\times \omega^{\omega}\) si consideri il [[id:a72d8a72-675b-472c-8c55-1d7746778acd][**-gioco]]: \(G^{**}_{\text{u}}(F)\). Indicato con \(A\coloneqq \pi_{X}(F)\):
a. se I ha una [[id:25fecfe5-10ce-4072-bba1-12024479dbca][strategia]] [[id:25fecfe5-10ce-4072-bba1-12024479dbca][vincente]] in \(G^{**}_{\text{u}}(F)\), allora \(A\) è magro in un aperto non vuoto di \(X\);
b. se II ha una [[id:25fecfe5-10ce-4072-bba1-12024479dbca][strategia]] [[id:25fecfe5-10ce-4072-bba1-12024479dbca][vincente]] in \(G^{**}_{\text{u}}(F)\) allora \(A\) è comagro.

** DA TOGLIERE

Dimostrazione teorema 2.12


** Teorema di Lusin-Sierpiński

*** Teorema di Lusin-Sierpiński 2.13
:PROPERTIES:
:BEAMER_env: alertblock
:END:

Sia \(X\) uno [[id:c0d47e62-8d50-44c0-984a-c115c0ea2c40][spazio polacco]]. Allora ogni [[id:648c8718-f653-4932-9c00-900d90560720][insieme analitico]] di \(X\) ha la [[id:a18bc557-1ac7-4d19-8cd8-ad3923e1a68f][Baire Property]].

*** Dimostrazione
:PROPERTIES:
:BEAMER_env: proof
:END:

Siccome \(\mathrm{BP}(X)\) è una [[id:75242464-a48e-4c0d-a56b-0cb5b3215ee2][\(\sigma\)-algebra]] allora è chiusa per complementi, e pertanto se ogni insieme coanalitico ha BP allora si è dimostrata la tesi.

Sia dunque \(C\) un insieme coanalitico e sia \(U \subseteq X\) un aperto. Posto \(A\coloneqq (X\setminus C)\cup U\), questo è un insieme analitico, e pertanto  esiste un chiuso \(F \subseteq X\times\omega^{\omega}\) tale che \(A=\pi_{X}(F)\).

Per il [[id:3c4f7c3f-7f63-4d59-9240-0c60d79e42ad][Teorema di Gale-Stewart]] 1.7 (e per il Lemma 2.11), allora, il [[id:a72d8a72-675b-472c-8c55-1d7746778acd][**-gioco \(G^{ * *}_{\text{u}}(F)\)]] è [[id:2f1132b9-a68c-42dc-b889-f9ea0565677f][determinato]], ed in particolare vale una tra le condizioni 1. e 2. del Teorema 2.12.

Per i [[id:8d136b11-9afd-48e7-aea3-dcc74393aff8][Teoremi]] 2.26 e 2.27, allora, il [[id:00eb3064-f9f9-47c4-9eac-473caaf438a7][gioco \(G^{**}(A) = G^{ * *}\left((X\setminus C) \cup U\right)\)]] è determinato: per il Lemma 2.8, quindi \(C\) ha la BP.

* \null

** Bibliografia minimale
\nocite{*}
\printbibliography
